-- MySQL Script generated by MySQL Workbench
-- Thu Jul  2 18:20:07 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema komiku
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `komiku` DEFAULT CHARACTER SET utf8 ;
USE `komiku` ;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comics` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `creator_id` BIGINT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `views` INT NOT NULL DEFAULT 0,
  `poster` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_comics_users1_idx` (`creator_id` ASC),
  INDEX `title_INDEX` (`title` ASC),
  CONSTRAINT `fk_comics_users1`
    FOREIGN KEY (`creator_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categories` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chapters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chapters` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `comic_id` BIGINT NOT NULL,
  `chapter_number` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_chapters_comics1_idx` (`comic_id` ASC),
  UNIQUE INDEX `uq_comic_chapter` (`comic_id` ASC, `chapter_number` ASC),
  CONSTRAINT `fk_chapters_comics1`
    FOREIGN KEY (`comic_id`)
    REFERENCES `comics` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `category_comic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `category_comic` (
  `comic_id` BIGINT NOT NULL,
  `category_id` BIGINT NOT NULL,
  PRIMARY KEY (`comic_id`, `category_id`),
  INDEX `fk_comics_has_categories_categories1_idx` (`category_id` ASC),
  INDEX `fk_comics_has_categories_comics1_idx` (`comic_id` ASC),
  CONSTRAINT `fk_comics_has_categories_comics1`
    FOREIGN KEY (`comic_id`)
    REFERENCES `comics` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comics_has_categories_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `comic_id` BIGINT NOT NULL,
  `user_id` BIGINT NULL,
  `parent_comment_id` BIGINT NULL,
  `content` TEXT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_ratings_users1_idx` (`user_id` ASC),
  INDEX `fk_ratings_comics1_idx` (`comic_id` ASC),
  INDEX `fk_comments_comments1_idx` (`parent_comment_id` ASC),
  CONSTRAINT `fk_ratings_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ratings_comics1`
    FOREIGN KEY (`comic_id`)
    REFERENCES `comics` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comments_comments1`
    FOREIGN KEY (`parent_comment_id`)
    REFERENCES `comments` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comic_rated_by_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comic_rated_by_user` (
  `comic_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `rating` TINYINT NOT NULL,
  PRIMARY KEY (`comic_id`, `user_id`),
  INDEX `fk_comics_has_users_users1_idx` (`user_id` ASC),
  INDEX `fk_comics_has_users_comics1_idx` (`comic_id` ASC),
  CONSTRAINT `fk_comics_has_users_comics1`
    FOREIGN KEY (`comic_id`)
    REFERENCES `comics` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comics_has_users_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chapter_pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chapter_pages` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `chapter_id` BIGINT NOT NULL,
  `page_number` INT NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_chapter_pages_chapters1_idx` (`chapter_id` ASC),
  UNIQUE INDEX `uq_chapter_page` (`chapter_id` ASC, `page_number` ASC),
  CONSTRAINT `fk_chapter_pages_chapters1`
    FOREIGN KEY (`chapter_id`)
    REFERENCES `chapters` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
