<?php

namespace App\Enums;

enum Action: string
{
    case OPTIONS = 'OPTIONS';

    // User
    case LOGIN = 'LOGIN';
    case REGISTER = 'REGISTER';
    case UPDATE_USER = 'UPDATE_USER';
    case DELETE_USER = 'DELETE_USER';


    // Category
    case GET_CATEGORIES = 'GET_CATEGORIES';
    case INSERT_CATEGORY = 'INSERT_CATEGORY';
    case UPDATE_CATEGORY = 'UPDATE_CATEGORY';
    case DELETE_CATEGORY = 'DELETE_CATEGORY';

    // Comic
    case GET_COMICS = 'GET_COMICS';
    case GET_COMIC_DETAIL = 'GET_COMIC_DETAIL';
    case INSERT_COMIC = 'INSERT_COMIC';
    case UPDATE_COMIC = 'UPDATE_COMIC';
    case DELETE_COMIC = 'DELETE_COMIC';

    // Comic chapter
    case GET_COMIC_CHAPTERS = 'GET_COMIC_CHAPTERS';
    case INSERT_COMIC_CHAPTERS = 'INSERT_COMIC_CHAPTERS';
    case UPDATE_COMIC_CHAPTER = 'UPDATE_COMIC_CHAPTER';
    case DELETE_COMIC_CHAPTER = 'DELETE_COMIC_CHAPTER';

    // Comic chapter page
    case GET_COMIC_CHAPTER_PAGES = 'GET_COMIC_CHAPTER_PAGES';
    case INSERT_COMIC_CHAPTER_PAGES = 'INSERT_COMIC_CHAPTER_PAGES';
    case UPDATE_COMIC_CHAPTER_PAGE = 'UPDATE_COMIC_CHAPTER_PAGE';
    case DELETE_COMIC_CHAPTER_PAGE = 'DELETE_COMIC_CHAPTER_PAGE';

    // Rating
    case INSERT_RATING = 'INSERT_RATING';
    case UPDATE_RATING = 'UPDATE_RATING';
    case DELETE_RATING = 'DELETE_RATING';

    // Comment
    case GET_COMMENTS = 'GET_COMMENTS';
    case INSERT_COMMENT = 'INSERT_COMMENT';
    case UPDATE_COMMENT = 'UPDATE_COMMENT';
    case DELETE_COMMENT = 'DELETE_COMMENT';

    // Reply
    case GET_REPLIES = 'GET_REPLIES';
    case INSERT_REPLY = 'INSERT_REPLY';
    case UPDATE_REPLY = 'UPDATE_REPLY';
    case DELETE_REPLY = 'DELETE_REPLY';
}